### ISSUE TITLE
A few sass-lint warnings

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1212]
### Steps to reproduce:
1. Create a file named ./.sass-lint.yml in the root directory.
2. Add the following contents and save:
   ```yml
files:
      include: ./static/css/*.scss

options:
      merge-default-rules: true

rules:
      force-attribute-nesting: 0
      force-element-nesting: 0
      force-pseudo-nesting: 0
      hex-length: 0
      hex-notation: 0
      leading-zero: 0
      no-color-keywords: 0
      no-color-literals: 0
      no-css-comments: 0
      no-ids: 0
      no-qualifying-elements: 0
      property-sort-order: 0
      quotes: 0
      single-line-per-selector: 0
      space-after-comma: 0
      url-quotes: 0
      zero-unit: 0
```
3. Install **sass-lint** as a dev dependency: `$ npm i sass-lint -D`
4. Add an npm package.json script for `"sass": "sass-lint -v -q",`
5. Run `$ npm run sass`

### Actual results:
```
$ npm run sass

...
✖ 131 problems (0 errors, 131 warnings)
```

Most seem to be formatting or mixed tabs-spaces, but a few could be actual errors (like some duplicated rules in a selector.
It should be pretty easy to add/remove other rules to the .sass-lint.yml file if we want to silence some rules for now until we can get down to a more reasonable number. Also pretty easy for me to jump in there and fix some formatting and the easy warnings to get the number down pretty quickly, then re-audit.
