### ISSUE TITLE
DOMException during capture

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1264]
I'm seeing this error regularly after #1250 landed:

```
console.info: shooting area 138 119 w/h 551 273 no max
console.log: mozilla-pageshot: checking items 3 100
console.error: 
DOMException
    - INDEX_SIZE_ERR = 1
    - DOMSTRING_SIZE_ERR = 2
    - HIERARCHY_REQUEST_ERR = 3
    - WRONG_DOCUMENT_ERR = 4
    - INVALID_CHARACTER_ERR = 5
    - NO_DATA_ALLOWED_ERR = 6
    - NO_MODIFICATION_ALLOWED_ERR = 7
    - NOT_FOUND_ERR = 8
    - NOT_SUPPORTED_ERR = 9
    - INUSE_ATTRIBUTE_ERR = 10
    - INVALID_STATE_ERR = 11
    - SYNTAX_ERR = 12
    - INVALID_MODIFICATION_ERR = 13
    - NAMESPACE_ERR = 14
    - INVALID_ACCESS_ERR = 15
    - VALIDATION_ERR = 16
    - TYPE_MISMATCH_ERR = 17
    - SECURITY_ERR = 18
    - NETWORK_ERR = 19
    - ABORT_ERR = 20
    - URL_MISMATCH_ERR = 21
    - QUOTA_EXCEEDED_ERR = 22
    - TIMEOUT_ERR = 23
    - INVALID_NODE_TYPE_ERR = 24
    - DATA_CLONE_ERR = 25
console.error: 
DOMException
    - INDEX_SIZE_ERR = 1
    - DOMSTRING_SIZE_ERR = 2
    - HIERARCHY_REQUEST_ERR = 3
    - WRONG_DOCUMENT_ERR = 4
    - INVALID_CHARACTER_ERR = 5
    - NO_DATA_ALLOWED_ERR = 6
    - NO_MODIFICATION_ALLOWED_ERR = 7
    - NOT_FOUND_ERR = 8
    - NOT_SUPPORTED_ERR = 9
    - INUSE_ATTRIBUTE_ERR = 10
    - INVALID_STATE_ERR = 11
    - SYNTAX_ERR = 12
    - INVALID_MODIFICATION_ERR = 13
    - NAMESPACE_ERR = 14
    - INVALID_ACCESS_ERR = 15
    - VALIDATION_ERR = 16
    - TYPE_MISMATCH_ERR = 17
    - SECURITY_ERR = 18
    - NETWORK_ERR = 19
    - ABORT_ERR = 20
    - URL_MISMATCH_ERR = 21
    - QUOTA_EXCEEDED_ERR = 22
    - TIMEOUT_ERR = 23
    - INVALID_NODE_TYPE_ERR = 24
    - DATA_CLONE_ERR = 25
console.error: mozilla-pageshot: 
  Message: TypeError: _this7.interactiveWorker is null
  Stack:
    destroy/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/lib/shooter.js:396:9
notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
```
