### ISSUE TITLE
no-resource-uri-leak breaks pageshot

### ISSUE THREAD

**Issue by rugk** [mozilla-services/pageshot#1700]
When [this addon](https://addons.mozilla.org/de/firefox/addon/no-resource-uri-leak/) is installed it breaks pageshot. It might be a general testpilot issue.

This is printed into the console Firefox was started from if I click on the page shot button when this add-on is used:
```
console.error: 
  Message: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.getResponseHeader]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js :: observe :: line 84"  data: no]
  Stack:
    observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js:84:26

console.error: 
  Message: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.getResponseHeader]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js :: observe :: line 84"  data: no]
  Stack:
    observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js:84:26

console.error: 
  Message: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.getResponseHeader]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js :: observe :: line 84"  data: no]
  Stack:
    observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js:84:26

console.error: 
  Message: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.getResponseHeader]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js :: observe :: line 84"  data: no]
  Stack:
    observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js:84:26


(firefox:14921): GLib-GObject-WARNING **: /build/glib2.0-ETetDu/glib2.0-2.48.0/./gobject/gsignal.c:3486: signal name 'load_complete' is invalid for instance '0x7ff6bc779c90' of type 'MaiAtkType139'
console.error: 
undefined
console.info: Skipping unknown attribute prefix on head
console.info: serializing setup took 4 milliseconds
console.info: shooting area 0 49 w/h 1907 547 no max
```

I also got this:
```
console.error: 
  Message: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.getResponseHeader]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js :: observe :: line 84"  data: no]
  Stack:
    observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js:84:26

console.error: 
  Message: Error: Permission denied to access property "document"
  Stack:
    @resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://min-vid/data/icon-overlay.js?cachebust=1475675647213:6:3
onEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:45:22
onEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:45:22
onChromeEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:91:16

console.error: 
  Message: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.getResponseHeader]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js :: observe :: line 84"  data: no]
  Stack:
    observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://no-resource-uri-leak/resource-filter/process/filter.js:84:26

console.info: Skipping unknown attribute prefix on head
console.info: serializing setup took 4 milliseconds
```

The addon broke horribly and the text was shown on the top left here on GitHub. Also it logged this:
```
console.info: shooting area 534 290 w/h 678 528 no max
console.info: shooting area 534 290 w/h 678 528 no max
```

Also reported there: https://notabug.org/desktopd/no-resource-uri-leak/issues/7
